name: Build Flet APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install flet
      - run: flet build apk
      - uses: actions/upload-artifact@v4  # اینجا اصلاح شد
        with:
          name: my-app
          path: build/apk/app-release.apk
